--- 
name: Deno linting and unit tests
on:
  workflow_call:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    env:
      tag: ${{fromJSON('["latest","dev"]')[github.ref == 'refs/heads/dev']}}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Cache Container
        id: image-cache
        uses: actions/cache@v3
        with:
          path: image
          key: starbot_container-${{ hashFiles('flake.*','**meson.build','src/**','subprojects/**') }}
      - name: Build Container
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          echo $tag
          podman run --rm -v ./:/wd:Z -w /wd docker.io/nixos/nix sh -c 'nix \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            build .#${{fromJSON('["StarBot","StarBot-Test"]')[github.ref == 'refs/heads/dev']}}
            cp result image
            rm result'
      - name: Load Image
        run: podman import image starbot:$tag
